name: Build Daily EPG1

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        delta: [0,1,2,3,4,5,6,7,8]

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install pip deps
        run: pip3 install -r scripts/requirements.txt
      - name: Install XMLTV lib
        run: sudo apt install xmltv
      - name: Run Python update_all_tv_guides script
        run: cd scripts/ && python3 ./update_raw_delta.py ${{ matrix.delta }}
      - name: Upload raw to artefact
        uses: actions/upload-artifact@v2
        with:
          name: raw-${{ matrix.delta }}
          path: raw
          
  computeAndPush:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install pip deps
        run: pip3 install -r scripts/requirements.txt
      - name: Install XMLTV lib
        run: sudo apt install xmltv
      - name: Clean old directory
        run: rm -R raw/*
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: raw
      - name: Download all artefacts
        uses: actions/download-artifact@v2
        with:
          path: raw
      - name: Clean Raw Directory
        run: cd raw && cp raw*/** ./ && rm -r raw*
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: raw
      - name: Run Python update_all_tv_guides script
        run: cd scripts/ && python3 ./update_all_tv_guides.py
      - name: Commit to origin
        run: |
          export now=$(date +"%d/%m/%Y %H:%M:%S-%Z")
          git config --global user.name 'XMLTV GithubAction'
          git config --global user.email 'XMLTV@users.noreply.github.com'
          git add --all
          git commit -am "Auto update TV guides ($now)"
          git push -f origin
