name: Build Daily EPG1

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        delta: [0,1,2,3,4,5,6,7,8]

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install pip deps
        run: pip3 install -r scripts/requirements.txt
      - name: Install XMLTV lib
        run: sudo apt install xmltv
      - name: Run Python script to collect daily raw
        run: cd scripts/ && python3 ./ga_update_raw_delta.py ${{ matrix.delta }}
      - name: Upload raw to artefact
        uses: actions/upload-artifact@v2
        with:
          name: raw-${{ matrix.delta }}
          path: raw
          
  computeAndPush:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install pip deps
        run: pip3 install -r scripts/requirements.txt
      - name: Install XMLTV lib
        run: sudo apt install xmltv
      - name: Remove old raw files
        run: python3 scripts/ga_remove_old_raw_files.py
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: raw
      - name: Download all artefacts
        uses: actions/download-artifact@v2
        with:
          path: raw
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: raw
      - name: Extract all raw files from raw-* directories
        run:  find raw-*/ -type f -print0 | xargs -0 mv -t . && rm -r raw-*
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: raw
      - name: Run Python script to compute xmltv files
        run: python3 scripts/ga_compute_xmltv.py
      - name: Commit & push force to origin
        run: bash scripts/ga_publish_git.sh
